markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: asupertramp
author: "Asupertramp"
name: "Asupertramp's Blog"
#url: http://www.panxw.com
#domain: www.panxw.com
all_categories: [
["languages", "Languages","/posts/languages.html"], 
["os", "OS","/posts/os.html"],
["ml", "ML","/posts/ml.html"],
["dl", "DL","/posts/dl.html"],
["math", "Math","/posts/math.html"],
["Libs", "Libs","/posts/libs.html"],
["reading_notes", "Reading Notes", "/posts/reading_notes.html"], 
["others", "Others","/posts/others.html"],
["about", "About","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
